apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 010438482862.dkr.ecr.us-east-1.amazonaws.com/frontend:4
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "true"
        ports:
        - containerPort: 3000
